// This file was automatically generated by braintrust pull. You can
// generate it again by running:
//  $ braintrust pull --project-name "lexiconic"
// Feel free to edit this file manually, but once you do, you should make sure to
// sync your changes with Braintrust by running:
//  $ braintrust push "braintrust/lexiconic.ts"

import braintrust from "braintrust";

const project = braintrust.projects.create({
  id: "f32b966f-8842-49df-bfd1-a3b40e32f08d",
  name: "lexiconic",
});

export const generateMetadata_4263 = project.prompts.create({
  id: "818dd7f3-9fb2-411a-86c6-ed47c0c1b6c5",
  name: "generate-metadata",
  slug: "generate-metadata-4263",
  version: "e8f726c6a0fea4b5",
  description: "",
  model: "gpt-5",
  messages: [
    {
      content:
        'Given the following word and language:\nWord: {{input.word}}\nLanguage: {{input.language}}\n\nReturn a JSON object with the following fields:\n- word: The input word.\n- language: The language of origin.\n- family: The linguistic family the language belongs to.\n- category: A brief, high-level category for the word’s meaning or usage (e.g., emotion, behavior, humor).\n- definition: A single, one-sentence English definition between 20 and 30 words. Neutral and formal in tone, consistent across all definitions. Provide only the definition, with no extra commentary. Sentence case.\n- literal: The literal or direct translation of the word (if applicable), otherwise an empty string.\n- usage_notes: A very short usage note to explain the the usage of the word. Your response should start with "Used", for example: "Used teasingly among friends at lakes or the seaside."\n- english_approx: The closest English word or phrase (if any).\n- phonetic: The phonetic respelling in English letters (no IPA). Hyphenate syllables and put the primary stressed syllable in ALL CAPS.\n- location: The city or region of origin of the word (e.g. Brazil or France). If you are unsure, return the most likely country based on the language.\n- lat: The latitude of the location.\n- lng: The longitude of the location.\n\nExample output:\n{\n  "word": "jayus",\n  "language": "Indonesian",\n  "family": "Austronesian",\n  "category": "humor/behavior",\n  "definition": "A joke that is so badly told or unfunny that it induces laughter because of its sheer awkwardness or inanity.",\n  "literal": "",\n  "usage_notes": "Used as a dad joke",\n  "english_approx": "dad joke",\n  "phonetic": "JAH-YOOS",\n  "location": "Indonesia",\n  "lat": -6.2088, \n  "lng": 106.8456\n}\n\nReturn your response as the JSON object only, with no additional text.',
      role: "system",
    },
  ],
  params: {
    use_cache: true,
    temperature: 0,
  },
  tools: [
    {
      type: "function",
      function: {
        name: "get_untranslatable_word",
        description:
          "Returns an object describing a single untranslatable word with language, family, category, concise definition, literal translation, usage notes, English approximation, phonetic, location, lat, and lng.",
        parameters: {
          required: [
            "word",
            "language",
            "family",
            "category",
            "definition",
            "literal",
            "usage_notes",
            "english_approx",
            "phonetic",
            "location",
            "lat",
            "lng",
          ],
          properties: {
            word: {
              type: "string",
              description: "The word in its working/script form to display.",
            },
            language: {
              type: "string",
              description: "Language name in English (e.g., 'Japanese').",
            },
            family: {
              type: "string",
              description: "Language family (e.g., 'Japonic').",
            },
            category: {
              type: "string",
              description:
                "Topical category or taxonomy (e.g., 'social/obligation').",
            },
            definition: {
              type: "string",
              description:
                "A single-sentence ~20–30 word definition ending with a period.",
            },
            literal: {
              type: "string",
              description: "Literal translation of the word/phrase.",
            },
            usage_notes: {
              type: "string",
              description:
                "Brief context on when/how it’s used or any social nuance.",
            },
            english_approx: {
              type: "string",
              description: "Closest concise English gloss or phrase.",
            },
            phonetic: {
              type: "string",
              description: "Syllabified/romanized pronunciation.",
            },
            location: {
              type: "string",
              description: "Location of origin.",
            },
            lat: {
              type: "number",
              description: "Latitude of location of origin.",
            },
            lng: {
              type: "number",
              description: "Longitude of location of origin.",
            },
          },
          type: "object",
        },
      },
    },
  ],
});