import { Info } from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";

interface FooterProps {
  isMapView?: boolean;
}

export function Footer({ isMapView = false }: FooterProps) {
  return (
    <footer className={`bg-background border-t border-border ${isMapView ? 'fixed bottom-0 left-0 right-0 z-10' : '-mt-px'}`}>
      <div className="p-6 text-center">
        <div className="flex items-center justify-center gap-2 text-xs text-muted-foreground uppercase letter-spacing-wide font-playfair">
          <span>A digital exploration of linguistic untranslatability</span>
          <Tooltip>
            <TooltipTrigger asChild>
              <button className="text-muted-foreground hover:text-foreground transition-colors">
                <Info className="h-3 w-3" />
              </button>
            </TooltipTrigger>
            <TooltipContent className="max-w-sm text-left normal-case">
              <p>
                Please note that definitions, pronunciations, and other metadata for Lexiconic were generated by AI (GPT-5 and GPT-4o-mini-TTS) and may not be fully accurate or precisely translated. To suggest edits or improvements, please{" "}
                <a href="mailto:hi@basecase.vc" className="hover:underline">
                  reach out
                </a>{" "}
                or submit a pull request.
              </p>
            </TooltipContent>
          </Tooltip>
        </div>
      </div>
    </footer>
  );
}
